services:
  - type: web
    name: vidshield-backend
    env: python
    rootDir: Detection/backend
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
